services:
  db:
    image: postgres:16
    container_name: thera_app_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Haslo123
      POSTGRES_DB: thera_app_local
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # GUI do bazy PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: thera_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@thera.app
      PGADMIN_DEFAULT_PASSWORD: Haslo123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"  # pgAdmin na http://localhost:8080
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    links:
      - db:postgres